joint_limits:
  arm_4_joint:
    has_velocity_limits: true
    max_velocity: 1.9634
    has_acceleration_limits: true
    max_acceleration: 0.39268
  arm_6_joint:
    has_velocity_limits: true
    max_velocity: 1.9634
    has_acceleration_limits: true
    max_acceleration: 0.39268
  sdh_thumb_2_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
  sdh_finger_23_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
  arm_5_joint:
    has_velocity_limits: true
    max_velocity: 1.9634
    has_acceleration_limits: true
    max_acceleration: 0.39268
  sdh_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
  arm_1_joint:
    has_velocity_limits: true
    max_velocity: 1.9634
    has_acceleration_limits: true
    max_acceleration: 0.39268
  base_placement_y_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 0.2
  torso_upper_neck_tilt_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.1
  torso_pan_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.1
  sdh_thumb_3_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
  sdh_finger_12_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
  arm_7_joint:
    has_velocity_limits: true
    max_velocity: 1.9634
    has_acceleration_limits: true
    max_acceleration: 0.39268
  lookat_y_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 0.2
  arm_2_joint:
    has_velocity_limits: true
    max_velocity: 1.9634
    has_acceleration_limits: true
    max_acceleration: 0.39268
  sdh_finger_13_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
  base_placement_theta_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 0.2
  base_placement_x_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 0.2
  arm_3_joint:
    has_velocity_limits: true
    max_velocity: 1.9634
    has_acceleration_limits: true
    max_acceleration: 0.39268
  sdh_finger_22_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
  torso_lower_neck_tilt_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.1
  lookat_x_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 0.2
  lookat_back_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 0.2
  lookat_z_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 0.2